### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mrskylab** [adamjstevenson/oauth-stripe-connect-php#1]
Hi Adam,
why I receive this error:
Fatal error: require_once(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/lib/php7.0')
I missed something.
Thanks
Nick

**Comment by copremesis** [comment]
http://upload.dragonwrench.com/uploads/Screen%20Shot%202016-12-06%20at%2010.00.48%20PM.png

this fixed it in my case

**Comment by phred** [comment]
@mrskylab you need to run `composer install` after downloading the repository so that Composer can pull down the project dependencies. See https://getcomposer.org
